import type { Config } from "tailwindcss";

const config: Config = {
  darkMode: "class",
  content: [
    "./pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./components/**/*.{js,ts,jsx,tsx,mdx}",
    "./app/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  theme: {
    extend: {
      colors: {
        canvas: "var(--canvas)",
        "surface-1": "var(--surface-1)",
        "surface-2": "var(--surface-2)",
        "surface-3": "var(--surface-3)",
        "t-primary": "var(--text-primary)",
        "t-secondary": "var(--text-secondary)",
        "t-tertiary": "var(--text-tertiary)",
        "b-subtle": "var(--border-subtle)",
        "b-hover": "var(--border-hover)",
        "b-focus": "var(--border-focus)",
        accent: {
          warm: "var(--accent-warm)",
          "warm-glow": "var(--accent-warm-glow)",
          cool: "var(--accent-cool)",
          "cool-glow": "var(--accent-cool-glow)",
          danger: "var(--accent-danger)",
          "danger-glow": "var(--accent-danger-glow)",
          DEFAULT: "var(--accent-warm)",
          violet: "var(--accent-cool)",
          lime: "var(--accent-cool)",
        },
        status: {
          success: "var(--accent-cool)",
          warning: "var(--accent-warm)",
          error: "var(--accent-danger)",
          info: "var(--status-info)",
        },
        cardBg: "var(--card-bg)",
        inputBg: "var(--input-bg)",
        primaryText: "var(--text-primary)",
        mutedText: "var(--text-secondary)",
        subtleBorder: "var(--border-subtle)",
      },
      fontFamily: {
        sans: [
          "var(--font-inter)",
          "Inter",
          "-apple-system",
          "BlinkMacSystemFont",
          '"Segoe UI"',
          "Roboto",
          "sans-serif",
        ],
        display: [
          "var(--font-inter)",
          "Inter",
          "-apple-system",
          "BlinkMacSystemFont",
          '"Segoe UI"',
          "Roboto",
          "sans-serif",
        ],
        mono: [
          "var(--font-jetbrains)",
          '"JetBrains Mono"',
          '"Cascadia Code"',
          "Consolas",
          "monospace",
        ],
        serif: [
          "var(--font-serif)",
          '"Source Serif 4"',
          '"Newsreader"',
          "Georgia",
          "serif",
        ],
      },
      fontSize: {
        display: ["2.5rem", { lineHeight: "1.15", fontWeight: "700" }],
        h1: ["1.75rem", { lineHeight: "1.25", fontWeight: "700" }],
        h2: ["1.25rem", { lineHeight: "1.3", fontWeight: "600" }],
        h3: ["1rem", { lineHeight: "1.4", fontWeight: "600" }],
        body: ["0.875rem", { lineHeight: "1.5", fontWeight: "400" }],
        caption: ["0.75rem", { lineHeight: "1.5", fontWeight: "400" }],
        micro: ["0.625rem", { lineHeight: "1.4", fontWeight: "500" }],
      },
      borderRadius: {
        DEFAULT: "0.5rem",
        lg: "0.75rem",
        xl: "1rem",
        "2xl": "1.25rem",
      },
      boxShadow: {
        "warm-glow": "0 0 20px var(--accent-warm-glow)",
        "cool-glow": "0 0 20px var(--accent-cool-glow)",
        subtle: "0 1px 3px 0 rgba(0, 0, 0, 0.15)",
        elevated: "0 8px 30px -6px rgba(0, 0, 0, 0.45)",
      },
    },
  },
  plugins: [],
};

export default config;
